dw_roi_1:
    roi_type: "cylinder"
    roi_radius_mm: 5.0
    ctr_vox_coords: [132,133,12]
    roi_height_mm: 3.0

dw_roi_2:
  roi_type: "cylinder"
  roi_radius_mm: 5.0
  ctr_vox_coords: [170,120,12]
  roi_height_mm: 3.0

dw_roi_3:
  roi_type: "cylinder"
  roi_radius_mm: 5.0
  ctr_vox_coords: [139,91,12]
  roi_height_mm: 3.0

dw_roi_4:
  roi_type: "cylinder"
  roi_radius_mm: 5.0
  ctr_vox_coords: [100,104,12]
  roi_height_mm: 3.0

dw_roi_5:
  roi_type: "cylinder"
  roi_radius_mm: 5.0
  ctr_vox_coords: [91,143,12]
  roi_height_mm: 3.0

dw_roi_6:
  roi_type: "cylinder"
  roi_radius_mm: 5.0
  ctr_vox_coords: [121,171,12]
  roi_height_mm: 3.0

dw_roi_7:
  roi_type: "cylinder"
  roi_radius_mm: 5.0
  ctr_vox_coords: [162,159,12]
  roi_height_mm: 3.0

dw_roi_8:
  roi_type: "cylinder"
  roi_radius_mm: 5.0
  ctr_vox_coords: [180,74,12]
  roi_height_mm: 3.0

dw_roi_9:
  roi_type: "cylinder"
  roi_radius_mm: 5.0
  ctr_vox_coords: [109,63,12]
  roi_height_mm: 3.0

dw_roi_10:
  roi_type: "cylinder"
  roi_radius_mm: 5.0
  ctr_vox_coords: [61,114,12]
  roi_height_mm: 3.0

dw_roi_11:
  roi_type: "cylinder"
  roi_radius_mm: 5.0
  ctr_vox_coords: [82,180,12]
  roi_height_mm: 3.0

dw_roi_12:
  roi_type: "cylinder"
  roi_radius_mm: 5.0
  ctr_vox_coords: [153,197,12]
  roi_height_mm: 3.0

dw_roi_13:
  roi_type: "cylinder"
  roi_radius_mm: 5.0
  ctr_vox_coords: [200,145,12]
  roi_height_mm: 3.0
