dw_roi_1:
    roi_type: "cylinder"
    roi_radius_mm: 5.0
    ctr_vox_coords: [132,132,12]
    roi_height_mm: 3.0

dw_roi_2:
  roi_type: "cylinder"
  roi_radius_mm: 5.0
  ctr_vox_coords: [169,117,12]
  roi_height_mm: 3.0

dw_roi_3:
  roi_type: "cylinder"
  roi_radius_mm: 5.0
  ctr_vox_coords: [139,88,12]
  roi_height_mm: 3.0

dw_roi_4:
  roi_type: "cylinder"
  roi_radius_mm: 5.0
  ctr_vox_coords: [100,101,12]
  roi_height_mm: 3.0

dw_roi_5:
  roi_type: "cylinder"
  roi_radius_mm: 5.0
  ctr_vox_coords: [90,140,12]
  roi_height_mm: 3.0

dw_roi_6:
  roi_type: "cylinder"
  roi_radius_mm: 5.0
  ctr_vox_coords: [121,168,12]
  roi_height_mm: 3.0

dw_roi_7:
  roi_type: "cylinder"
  roi_radius_mm: 5.0
  ctr_vox_coords: [159,157,12]
  roi_height_mm: 3.0

dw_roi_8:
  roi_type: "cylinder"
  roi_radius_mm: 5.0
  ctr_vox_coords: [178,72,12]
  roi_height_mm: 3.0

dw_roi_9:
  roi_type: "cylinder"
  roi_radius_mm: 5.0
  ctr_vox_coords: [109,57,12]
  roi_height_mm: 3.0

dw_roi_10:
  roi_type: "cylinder"
  roi_radius_mm: 5.0
  ctr_vox_coords: [61,108,12]
  roi_height_mm: 3.0

dw_roi_11:
  roi_type: "cylinder"
  roi_radius_mm: 5.0
  ctr_vox_coords: [82,175,12]
  roi_height_mm: 3.0

dw_roi_12:
  roi_type: "cylinder"
  roi_radius_mm: 5.0
  ctr_vox_coords: [150,194,12]
  roi_height_mm: 3.0

dw_roi_13:
  roi_type: "cylinder"
  roi_radius_mm: 5.0
  ctr_vox_coords: [200,142,12]
  roi_height_mm: 3.0
