dw_roi_1:
    roi_type: "cylinder"
    roi_radius_mm: 5.0
    ctr_vox_coords: [129,129,13]
    roi_height_mm: 3.0

dw_roi_2:
  roi_type: "cylinder"
  roi_radius_mm: 5.0
  ctr_vox_coords: [167,118,13]
  roi_height_mm: 3.0

dw_roi_3:
  roi_type: "cylinder"
  roi_radius_mm: 5.0
  ctr_vox_coords: [141,89,13]
  roi_height_mm: 3.0

dw_roi_4:
  roi_type: "cylinder"
  roi_radius_mm: 5.0
  ctr_vox_coords: [101,97,13]
  roi_height_mm: 3.0

dw_roi_5:
  roi_type: "cylinder"
  roi_radius_mm: 5.0
  ctr_vox_coords: [88,136,13]
  roi_height_mm: 3.0

dw_roi_6:
  roi_type: "cylinder"
  roi_radius_mm: 5.0
  ctr_vox_coords: [116,166,13]
  roi_height_mm: 3.0

dw_roi_7:
  roi_type: "cylinder"
  roi_radius_mm: 5.0
  ctr_vox_coords: [154,157,13]
  roi_height_mm: 3.0

dw_roi_8:
  roi_type: "cylinder"
  roi_radius_mm: 5.0
  ctr_vox_coords: [180,74,13]
  roi_height_mm: 3.0

dw_roi_9:
  roi_type: "cylinder"
  roi_radius_mm: 5.0
  ctr_vox_coords: [113,55,13]
  roi_height_mm: 3.0

dw_roi_10:
  roi_type: "cylinder"
  roi_radius_mm: 5.0
  ctr_vox_coords: [60,102,13]
  roi_height_mm: 3.0

dw_roi_11:
  roi_type: "cylinder"
  roi_radius_mm: 5.0
  ctr_vox_coords: [75,171,13]
  roi_height_mm: 3.0

dw_roi_12:
  roi_type: "cylinder"
  roi_radius_mm: 5.0
  ctr_vox_coords: [143,193,13]
  roi_height_mm: 3.0

dw_roi_13:
  roi_type: "cylinder"
  roi_radius_mm: 5.0
  ctr_vox_coords: [195,145,13]
  roi_height_mm: 3.0
