dw_roi_1:
    roi_type: "cylinder"
    roi_radius_mm: 5.0
    ctr_vox_coords: [129,130,15]
    roi_height_mm: 3.0

dw_roi_2:
  roi_type: "cylinder"
  roi_radius_mm: 5.0
  ctr_vox_coords: [168,118,15]
  roi_height_mm: 3.0

dw_roi_3:
  roi_type: "cylinder"
  roi_radius_mm: 5.0
  ctr_vox_coords: [139,88,15]
  roi_height_mm: 3.0

dw_roi_4:
  roi_type: "cylinder"
  roi_radius_mm: 5.0
  ctr_vox_coords: [100,98,15]
  roi_height_mm: 3.0

dw_roi_5:
  roi_type: "cylinder"
  roi_radius_mm: 5.0
  ctr_vox_coords: [88,137,15]
  roi_height_mm: 3.0

dw_roi_6:
  roi_type: "cylinder"
  roi_radius_mm: 5.0
  ctr_vox_coords: [116,166,15]
  roi_height_mm: 3.0

dw_roi_7:
  roi_type: "cylinder"
  roi_radius_mm: 5.0
  ctr_vox_coords: [156,156,15]
  roi_height_mm: 3.0

dw_roi_8:
  roi_type: "cylinder"
  roi_radius_mm: 5.0
  ctr_vox_coords: [180,73,15]
  roi_height_mm: 3.0

dw_roi_9:
  roi_type: "cylinder"
  roi_radius_mm: 5.0
  ctr_vox_coords: [112,55,15]
  roi_height_mm: 3.0

dw_roi_10:
  roi_type: "cylinder"
  roi_radius_mm: 5.0
  ctr_vox_coords: [60,103,15]
  roi_height_mm: 3.0

dw_roi_11:
  roi_type: "cylinder"
  roi_radius_mm: 5.0
  ctr_vox_coords: [77,172,15]
  roi_height_mm: 3.0

dw_roi_12:
  roi_type: "cylinder"
  roi_radius_mm: 5.0
  ctr_vox_coords: [146,195,15]
  roi_height_mm: 3.0

dw_roi_13:
  roi_type: "cylinder"
  roi_radius_mm: 5.0
  ctr_vox_coords: [198,144,15]
  roi_height_mm: 3.0
