name: Feature request
description: Please feel free to submitting your idea in the discussions first.
title: "ENH: <Please write a comprehensive title after the 'ENH: ' prefix>"

body:
- type: markdown
  attributes:
    value: >
      If you're looking to request a new feature or change in functionality,
      including adding or changing the meaning of arguments to an existing
      function, please post your idea on the the discussions "ideas" to
      to explain your reasoning in addition to opening an issue.

- type: textarea
  attributes:
    label: "Proposed new feature or change:"
  validations:
    required: true
