# ====================================================================================================================
# Global settings
# ====================================================================================================================
global:
  output_directory: "output_180" # use forward slashes in filepath
  overwrite_existing_output: True

# ====================================================================================================================
# PHANTOM/EXPERIMENT configuration
# ====================================================================================================================
phantom_experiment:
  phantom_manufacturer: "caliber_mri" # options include [caliber_mri]
  phantom_type: "system_phantom"      # options include [system_phantom]
  phantom_serial_number: "130-0093"   # for CalibreMRI phantoms SN has format XXX-XXXX
  field_strength_tesla: 3.0           # options include [1.5, 3.0]
  temperature_celsius: 20.0           # will match to closest experimental reference data


# ====================================================================================================================
# DICOM sorting options
# ====================================================================================================================
dicom_sorting:
  scan_protocol : "auckland_cam_3p0T"   # options include [siemens_skyra_3p0T, philips_marlin_1p5T, auckland_cam_3p0T]
  scan_protocol_options: ["siemens_skyra_3p0T", "philips_marlin_1p5T"]
  save_sorted_images: False # future feature (not implemented)


# ====================================================================================================================
# ROI detection options
# ====================================================================================================================
roi_detection:
  template_name: "systemlite_siemens_vida_3p0T_180degrees"   # options include [siemens_skyra_3p0T, systemlite_siemens_vida_3p0T]
  registration_method: "correl-GD"
  save_mask_images: False                         # future feature (not implemented)
  partial_fov: True


# ====================================================================================================================
# Curve fitting options
# ====================================================================================================================
curve_fitting:
  # -----------------------------------------------------------------------------------------------------------------
  # PRE-PROCESSING
  # -----------------------------------------------------------------------------------------------------------------
  averaging: "voxels_in_ROI"              # options include [none, voxels_in_ROI]
  normalisation: "voxel_max"              # options include [none, voxel_max, roi_max]
  exclude: "clipped"                      # options include [none, clipped]
  percent_clipped_threshold: 100           # [0, 100] for parital clipping, the number of unclipped/clean voxels required across all measurements in the ROI
  # -----------------------------------------------------------------------------------------------------------------
  # MODEL OPTIONS
  # -----------------------------------------------------------------------------------------------------------------
  t1_vfa_options:
    fitting_models: ["2_param"]
    use_2D_roi: False                     #  to use a 3D ROI or a central 2D slice ROI
  t2_star_ge_options:
    fitting_models: [ "2_param" ]

  # -----------------------------------------------------------------------------------------------------------------
  # OUTPUT OPTIONS
  # -----------------------------------------------------------------------------------------------------------------
  save_voxel_data: True
  save_parameter_maps: False # future feature (not implemented)


